#!/usr/bin/env python3
"""
Environment setup helper for Smiley's Blog deployment
"""

import secrets
import os

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_hex(32)

def create_env_file():
    """Create a .env file with necessary environment variables"""
    
    print("🔧 Setting up environment for Smiley's Blog")
    print("=" * 50)
    
    # Generate secret key
    secret_key = generate_secret_key()
    print(f"✅ Generated SECRET_KEY (first 16 chars): {secret_key[:16]}...")
    print("   Full key will be saved to .env file")
    
    # Environment variables
    env_vars = {
        'SECRET_KEY': secret_key,
        'FLASK_ENV': 'production',
        'DATABASE_URL': 'sqlite:///instance/site.db',  # Default to SQLite
        'UPLOAD_FOLDER': 'static/uploads'
    }
    
    # Ask for optional admin credentials
    print("\n📝 Optional: Set up initial admin user")
    admin_user = input("Admin username (press Enter to skip): ").strip()
    if admin_user:
        admin_pass = input("Admin password: ").strip()
        if admin_pass:
            env_vars['ADMIN_USER'] = admin_user
            env_vars['ADMIN_PASSWORD'] = admin_pass
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write("# Smiley's Blog Environment Configuration\n")
        f.write("# Generated by setup_env.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("\n✅ Created .env file with configuration")
    print("📄 To view the full SECRET_KEY, check the .env file")
    print("\n📋 Next steps:")
    print("1. Review and modify .env file if needed")
    print("2. For production, update DATABASE_URL to use PostgreSQL")
    print("3. Run: python app.py (development) or python start_production.py (production)")
    print("4. Create admin user: python scripts/create_admin.py")
    
    print("\n🚀 Ready for deployment!")
    
    # Option to display full key if requested
    show_key = input("\n🔐 Show full SECRET_KEY? (y/N): ").strip().lower()
    if show_key == 'y':
        print(f"\n🔑 Full SECRET_KEY: {secret_key}")
        print("⚠️  Keep this secret! Don't share it publicly.")

if __name__ == '__main__':
    create_env_file()