"""Add enhanced Post model fields

Revision ID: 2cbdb1f2cfa3
Revises: 87042026760f
Create Date: 2026-01-17 14:33:15.493947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbdb1f2cfa3'
down_revision = '87042026760f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('scheduled_publish_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('status')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
