"""Add cascade delete for comments when post is deleted

Revision ID: fd8c8a944542
Revises: 605404d85372
Create Date: 2026-01-18 14:10:23.067149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c8a944542'
down_revision = '605404d85372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_search_fts_data')
    op.drop_table('post_search_fts')
    op.drop_table('post_search_fts_idx')
    op.drop_table('post_search_fts_config')
    op.drop_table('post_search_fts_content')
    op.drop_table('post_search_fts_docsize')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    op.create_table('post_search_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_search_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True),
    sa.Column('c5', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_search_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('post_search_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('post_search_fts',
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('content', sa.NullType(), nullable=True),
    sa.Column('summary', sa.NullType(), nullable=True),
    sa.Column('category', sa.NullType(), nullable=True),
    sa.Column('tags', sa.NullType(), nullable=True),
    sa.Column('post_id', sa.NullType(), nullable=True)
    )
    op.create_table('post_search_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
